env:
  commonjs: true
  es6: true
  node: true
extends:
  - standard
  - eslint:recommended
  - prettier
  - plugin:prettier/recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 11
  sourceType: module
plugins:
  - prettier
rules: {}